---
- name: Create Users on Target Systems (AAP Survey Version)
  hosts: all
  become: yes
  gather_facts: yes
  # NO vars_prompt section!

  tasks:
    - name: Ensure required groups exist (Ubuntu)
      group:
        name: "{{ item }}"
        state: present
      loop:
        - users
        - sudo
      when: ansible_distribution == "Ubuntu"

    - name: Create user without sudo
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        groups: users
        shell: "/bin/bash"  # Fixed: was using undefined variable
        create_home: yes
        state: present
      when: add_sudo == "no"

    - name: Create user with sudo (Ubuntu)
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        groups: 
          - users
          - sudo
        shell: "/bin/bash"  # Fixed: was using undefined variable
        create_home: yes
        state: present
      when: add_sudo == "yes" and ansible_distribution == "Ubuntu"

    - name: Display created users
      debug:
        msg: "User {{ username }} created successfully with sudo: {{ add_sudo }}"