---
- name: Configure Firewall Rules (AAP Survey Version)
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install UFW (Ubuntu)
      apt:
        name: ufw
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Reset UFW to defaults (Ubuntu)
      ufw:
        state: reset
      when: ansible_distribution == "Ubuntu"

    - name: Set UFW default policies (Ubuntu)
      ufw:
        default: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: incoming, policy: deny }
        - { direction: outgoing, policy: allow }
      when: ansible_distribution == "Ubuntu"

    - name: Add basic firewall rules
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
        comment: "Basic Service"
      loop:
        - "22"   # SSH
        - "80"   # HTTP
        - "443"  # HTTPS
      when: ansible_distribution == "Ubuntu"

    - name: Add custom firewall rule
      ufw:
        rule: "{{ rule_action }}"
        port: "{{ custom_port }}"
        proto: "{{ protocol }}"
        comment: "Custom Rule - {{ custom_port }}/{{ protocol }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - custom_port is defined
        - custom_port != ""

    - name: Enable UFW (Ubuntu)
      ufw:
        state: enabled
        logging: 'on'
      when: ansible_distribution == "Ubuntu"

    - name: Get UFW status
      command: ufw status numbered
      register: ufw_status
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Display firewall status
      debug:
        var: ufw_status.stdout_lines
      when: ansible_distribution == "Ubuntu"