---
- name: Manage Individual Firewall Rules (Shell Commands Version)
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install UFW (Ubuntu)
      apt:
        name: ufw
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Check if UFW is installed
      command: which ufw
      register: ufw_installed
      changed_when: false
      failed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Add firewall rule with source IP restriction
      command: "ufw allow from {{ source_ip }} to any port {{ port_number }} proto {{ protocol }} comment 'Rule for {{ port_number }}/{{ protocol }} from {{ source_ip }}'"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "add"
        - source_ip is defined
        - source_ip != ""
        - source_ip != "any"

    - name: Add firewall rule without source IP restriction
      command: "ufw allow {{ port_number }}/{{ protocol }} comment 'Rule for {{ port_number }}/{{ protocol }} from any'"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "add"
        - (source_ip is not defined or source_ip == "" or source_ip == "any")

    - name: Remove firewall rule with source IP
      command: "ufw delete allow from {{ source_ip }} to any port {{ port_number }} proto {{ protocol }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "remove"
        - source_ip is defined
        - source_ip != ""
        - source_ip != "any"
      ignore_errors: yes

    - name: Remove firewall rule without source IP
      command: "ufw delete allow {{ port_number }}/{{ protocol }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "remove"
        - (source_ip is not defined or source_ip == "" or source_ip == "any")
      ignore_errors: yes

    - name: List current firewall rules
      command: ufw status numbered
      register: current_rules
      changed_when: false
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "list"

    - name: Display current firewall rules
      debug:
        var: current_rules.stdout_lines
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "list"

    - name: Get updated firewall status after changes
      command: ufw status numbered
      register: updated_rules
      changed_when: false
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action in ["add", "remove"]

    - name: Display updated firewall rules
      debug:
        msg: |
          Action: {{ action }}
          Port: {{ port_number }}/{{ protocol }}
          Source IP: {{ source_ip | default('any') }}
          Status: {{ 'Completed' if updated_rules.rc == 0 else 'Failed' }}
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action in ["add", "remove"]

    - name: Display error if UFW not available
      debug:
        msg: "UFW is not available on this system"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc != 0