---
- name: Manage Service-Based Firewall Rules (Shell Commands Version)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    service_ports:
      apache: ["80", "443"]
      mysql: ["3306"]
      postgresql: ["5432"]
      ssh: ["22"]
      ftp: ["21", "20"]
      dns: ["53"]
      smtp: ["25", "587"]
      imap: ["143", "993"]
      pop3: ["110", "995"]
      mongodb: ["27017"]
      redis: ["6379"]
      elasticsearch: ["9200", "9300"]
      docker: ["2376", "2377"]
      kubernetes: ["6443", "8080"]
      jenkins: ["8080"]
      grafana: ["3000"]
      prometheus: ["9090"]

  tasks:
    - name: Install UFW (Ubuntu)
      apt:
        name: ufw
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Check if UFW is installed
      command: which ufw
      register: ufw_installed
      changed_when: false
      failed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Fail if service not supported
      fail:
        msg: "Service '{{ service_name }}' is not supported. Available services: {{ service_ports.keys() | join(', ') }}"
      when: 
        - service_name not in service_ports.keys()
        - service_name != "custom"

    - name: Add service-based firewall rules
      command: "ufw allow {{ item }}/{{ protocol }} comment '{{ service_name | upper }} service - {{ item }}/{{ protocol }}'"
      loop: "{{ service_ports[service_name] }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "add"
        - service_name in service_ports.keys()

    - name: Remove service-based firewall rules
      command: "ufw delete allow {{ item }}/{{ protocol }}"
      loop: "{{ service_ports[service_name] }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "remove"
        - service_name in service_ports.keys()
      ignore_errors: yes

    - name: Add custom service rule
      command: "ufw allow {{ custom_port }}/{{ protocol }} comment 'Custom service - {{ custom_port }}/{{ protocol }}'"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "add"
        - service_name == "custom"
        - custom_port is defined

    - name: Remove custom service rule
      command: "ufw delete allow {{ custom_port }}/{{ protocol }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "remove"
        - service_name == "custom"
        - custom_port is defined
      ignore_errors: yes

    - name: Get current firewall status
      command: ufw status numbered
      register: service_rules_status
      changed_when: false
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0

    - name: Display service configuration result
      debug:
        msg: |
          Service: {{ service_name }}
          Action: {{ action }}
          Ports configured: {{ service_ports[service_name] | join(', ') if service_name in service_ports.keys() else custom_port }}
          Protocol: {{ protocol }}
          Status: Completed
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0

    - name: Display current firewall rules
      debug:
        var: service_rules_status.stdout_lines
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0