---
- name: Manage Multiple Firewall Ports (Shell Commands Version)
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install UFW (Ubuntu)
      apt:
        name: ufw
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Check if UFW is installed
      command: which ufw
      register: ufw_installed
      changed_when: false
      failed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Convert port list to array
      set_fact:
        port_array: "{{ port_list.split(',') | map('trim') | list }}"
      when: port_list is defined and port_list != ""

    - name: Add multiple firewall rules
      command: "ufw allow {{ item }}/{{ protocol }} comment 'Bulk rule for {{ item }}/{{ protocol }}'"
      loop: "{{ port_array }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "add"
        - port_array is defined

    - name: Remove multiple firewall rules
      command: "ufw delete allow {{ item }}/{{ protocol }}"
      loop: "{{ port_array }}"
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0
        - action == "remove"
        - port_array is defined
      ignore_errors: yes

    - name: Get final firewall status
      command: ufw status numbered
      register: final_status
      changed_when: false
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0

    - name: Display processed ports
      debug:
        msg: |
          Action: {{ action }}
          Ports processed: {{ port_array | join(', ') }}
          Protocol: {{ protocol }}
          Status: Completed
      when: 
        - port_array is defined
        - ufw_installed.rc == 0

    - name: Display final firewall status
      debug:
        var: final_status.stdout_lines
      when: 
        - ansible_distribution == "Ubuntu"
        - ufw_installed.rc == 0